bookmark_project/bookmark/urls.py
from django.urls import path

from .views import BookmarkList, BookmarkCreate, BookmarkUpdate, BookmarkDelete, BookmarkDetail

# namespace 이름 공간
# 다른 앱들과 url pattern 이름이 겹치는 것을 방지하기 위해서 사용
# namespace라는 인수가 존재
# 2.0 버전 이후에는 app_name으로 namespace 설정

# app_name 이름은 자유
app_name = 'bookmark'
urlpatterns = [
    # path(url pattern, view, url pattern name),
    # 함수형 뷰 : 이름만
    # 클래스형 뷰 : 이름.as_view()
    # path, uuid, slug, int, str  --> converter --> custom converter로 만들어서 쓸 수 있다.
    # slug --> ex) wordpress-powers-30-percent-internet
    # map/127.2222-34.3412/
    # convert -> location
    # map/<location:valu>/
    path('detail/<int:pk>/', BookmarkDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', BookmarkDelete.as_view(), name='delete'),
    path('update/<int:pk>/', BookmarkUpdate.as_view(), name='update'),
    path('create/', BookmarkCreate.as_view(), name='create'),
    path('', BookmarkList.as_view(), name='index'),
]

bookmark_project/bookmark/models.py
from django.db import models

# Create your models here.
# 모델의 형태 - 클래스

class Bookmark(models.Model):
    site_name = models.CharField(max_length=50)
    url = models.URLField()  # character type 으로 입력받는다
    contents = models.TextField(blank=True)
    # 작성자 -> 로그인한 유저 정보를 찾아서 추가
    # 작성자가 로그인한 유저인지 알 수 없음
    # -> 모델 저장 직전에 직접 코드로 처리

    # 작성일 -> 서버 시간을 읽어서 timestamp값을 만들어 추가
    # 자동 옵션 auto_now, auto_now_add
    created = models.DateTimeField(auto_now_add=True)
    # auto_now_add : 처음 저장 될때의 시간을 자동으로 처리 --> 갱신을 할때마다 저장해줌

    # DB에 적용 : makemigrations, migrate
    # python3 manage.py makemigrations bookmark
    # python3 manage.py migrate bookmark 0001

    # 관리자 페이지 목록에 표시될 내용
    # 확인 메시지에 출력되는 내용을 만들기 위해
    def __str__(self):
        return "Site name : " + self.site_name + " (URL : " + self.url +")"

    # 모델 클래스가 수정됐다고 해서 항상 migrate 해야 하는 것은 아니다.
    # DB에 변경 사항이 반영되어야 할 항목들만 migrate를 한다.

    # 메타 클래스는 옵션 클래스 - 내가 상속을 받았는데, 속성값에 변경이 필요하다면
    class Meta:
        # 정렬 : 필드이름 -> 필드값 오름차순, -필드이름 -> 필드값 내림차순
        ordering = ['-id']
    # class Meta --> DB에 저장 필요

bookmark_project/bookmark/views.py
from django.shortcuts import render


# Create your views here.

# 뷰 종류

# 클래스형 뷰 함수형 뷰는 서로 상호 기능 제약이 거의 없다. (함수형뷰 클래스형뷰로 만들수 있고, 클래스형뷰 함수형뷰로 만들 수 있다.)
# CRUDL에 특별한 처리를 추가해야 되는 경우
# 함수형뷰는 자유도가 클래스형 뷰에 비해서 높다.
# 함수형 : def 뷰이름(request,[추가 인수]):
#           처리할 내용
# 처리할 코드를 직접 다 개발자가 작성
#


# CRUDL 에 관련 기능은 자주 사용하기 때문에 장고에서 제네릭 만들어놓음
# 클래스형뷰는 생산성이 함수형뷰에 비해 높다.
# 클래스형 : class 뷰이름(제네릭뷰):
#               처리할 내용
# 제네릭 기능 외에 추가적인 기능을 개발자가 작성
# 메서드 방식 - 커스터마이징 관련된 메서드를 찾아야 한다.

# CRUD_L
from .models import Bookmark

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic.list import ListView

from django.views.generic.detail import DetailView

# 클래스형 뷰의 이름은 자유
class BookmarkList(ListView):
    model = Bookmark
    # 템플릿 종류 바꾸거나
    # 읽어오는 데이터 변경하거나
    # 페이지네이션을 걸거나
    # 검색 쿼리를 적용하거나
    # 권한 체크

# 뷰를 만들었다 -> URL 연결
# CRUD 뷰를 만들고, URL 연결까지

class BookmarkCreate(CreateView):
    model = Bookmark
    # fields는 사용자가 입력할 모델 필드를 정하는 것
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_create'
    success_url = '/'
    # _create
    # _form

class BookmarkUpdate(UpdateView):
    model = Bookmark
    fields = ['site_name', 'url', 'contents']
    template_name_suffix = '_update'
    success_url = '/'
    # _update
    # _form

class BookmarkDelete(DeleteView):
    model = Bookmark
    template_name_suffix = '_delete'
    success_url = '/'
    # _confirm_delete

class BookmarkDetail(DetailView):
    model = Bookmark

bookmark_project/bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}

{% block title %}
Bookmark Create
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8">
        <form action="" method="post">
            {% csrf_token %}   <!-- 보안관련해서 써주는 것 -->
            <div style = "margin-top: 20px" class="alert alert-warning" role="alert">사이트 이름과 URL을 정확히 입력해주세요!</div>
                {{form.as_p}}
                <input type="submit" value="Create" style="width:200px">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark_project/bookmark/templates/bookmark/bookmark_delete.html
{% extends 'base.html' %}

{% block title %}
Bookmark Delete
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-md-8 col-xl-12">
        <form action="" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete Ok">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

bookmark_project/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}
Bookmark Detail
{% endblock %}

{% block content %}
    <div class="card" style="width: 18rem; margin-top: 50px;">
      <div class="card-body">
        <h5 class="card-title">{{object.site_name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted"><a href="{{object.url}}">{{object.url}}</a></h6>
        <p class="card-text">{{object.contents}}</p>
        <a href="{% url 'bookmark:update' object.id %}" class="card-link btn btn-outline-warning">수정</a>
        <a href="{% url 'bookmark:delete' object.id %}" class="card-link btn btn-outline-danger">삭제</a>
      </div>
    </div>
{% endblock %}

bookmark_project/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
<!--//
CRUDL - 복수 객체, 단일 객체
C - 객체 생성
R - 단일 객체 -> object
U - 단일 객체 -> object
D - 단일 객체 -> object
L - 복수 객체 -> object_list
//-->
{% block title %}
Bookmark List
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div style="margin: 20px 0 20px 0">
            <a href="{% url 'bookmark:create'  %}" class="btn btn-primary">Add Bookmark</a><br>
        </div>
        {# bookmark 목록 출력하기 #}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col" style="text-align:middle;">순</th>
                    <th scope="col">사이트명</th>
                    <th scope="col">링크</th>
                    <th scope="col">수정</th>
                    <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <td style="vertical-align: middle;"> {{object.id}} </td>
                    <td style="vertical-align: middle;">
                        <a href="{% url 'bookmark:detail' object.id %}">{{object.site_name}}</a><br>
                    </td>
                    <td><a href="{{object.url}}" target="_blank" class="card-link btn btn-link">Link</a></td>
                    <td><a href="{% url 'bookmark:update' object.id %}" class="card-link btn btn-warning">Modify</a></td>
                    <td><a href="{% url 'bookmark:delete' object.id %}" class="card-link btn btn-danger">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col"></div>
</div>
    <!-- object.id 쓰는 이유 : bookmark/urls.py 에서 detail/<converter> 부분 받아오겠다라는 의미 -->
{% endblock %}

bookmark_project/bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}

{% block title %}
Bookmark Update
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create">
</form>
{% endblock %}