dstagram_project/photo/urls.py
from .views import *

from django.urls import path

app_name = 'photo'

urlpatterns = [
    path('slist/', PhotoSaveList.as_view(), name='slist'),
    path('saved/<int:photo_id>', PhotoSaved.as_view(), name='saved'),
    path('like/<int:photo_id>/', PhotoLike.as_view(), name='like'),
    path('', PhotoList.as_view(), name='index'),
    path('create/', PhotoCreate.as_view(), name='create'),
    path('update/<int:pk>/', PhotoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/', PhotoDetail.as_view(), name='detail'),
    path('delete/<int:pk>/', PhotoDelete.as_view(), name='delete'),
]

dstagram_project/photo/models.py
from django.db import models

# Create your models here.
# 기본 모델

'''

작성자 : author
본문글 : text
사진 : image
작성일 : created
수정일 : updated

+ tag, like
-- comment

'''
# from django.contrib.auth.models import User
# reverse --> url pattern 이름을 가지고 주소를 만들어주는 함수
from django.urls import reverse
# User 모델을 확장 가능
# settings.AUTH_USER_MODEL
from django.contrib.auth import get_user_model

class Photo(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='photos')   # ForeignKey(User, 삭제 시 동작, 연관 이름)
    # models.ForeignKey(get_user_model(), )  --> 확장할 거라면 요렇게 쓰는 걸 추천
    # CASCADE --> 연속해서 지운다. 탈퇴하면 사진도 싹 지운다.
    # PROTECT --> 사진 다 안지우면 너 탈퇴 안됨 - 탈퇴 프로세스에 사진을 우선 삭제하고 탈퇴시킨다.
    # 특정값으로 셋팅 -
    # reletaed_name 으로 연관 데이터를 얻을 수 없다면 쿼리를 별도로 실행해야 한다.
    # 내 프로필 페이지 - 내가 올린 사진만 뜬다.
    # pillow --> python에서 image를 올리기 위한 라이브러리리
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m.%d')   # %Y/%m/%d --> 자동으로 연/월/일 생성해준다.
    # upload_to 는 함수를 사용해서 폴더를 동적으로 설정할 수 있다.
    created = models.DateTimeField(auto_now_add=True)   # 처음 생성할 때만 지정
    updated = models.DateTimeField(auto_now=True)   # 처음 생성할때, 수정할때마다 지정

    like = models.ManyToManyField(get_user_model(), related_name='like_post')
    saved = models.ManyToManyField(get_user_model(), related_name='saved_post')

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        # detail/<int:pk>/ 여기에 들어갈 값을 self.id로 던져준다.
        return reverse('photo:detail', args=[self.id])

dstagram_project/photo/views.py
from django.shortcuts import render

from django.shortcuts import redirect

# Create your views here.
# CRuDL - 이미지를 띄우는 방법
# 제네릭 뷰
# 쿼리셋 변경하기, context_data 추가하기, 권한 체크
# 함수형 뷰 <-> 클래스형 뷰

from .models import Photo

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.views.generic.list import ListView

from django.views.generic.detail import DetailView

from django.http import HttpResponseRedirect

from django.http import HttpResponseForbidden

from django.contrib import messages

from django.shortcuts import redirect

class PhotoList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'


class PhotoCreate(CreateView):
    model = Photo
    fields = ['author', 'image', 'text']
    template_name_suffix = '_create'

    def form_valid(self, form):
        # 입력된 자료가 올바른지 체크
        form.instance.author_id = self.request.user.id  # form.instance.[필드명]_id
        if form.is_valid():
            # 올바르다면,
            # form : 모델 폼
            form.instance.save()
            return redirect('/')
        else:
            # 올바르지 않다면,
            return self.render_to_response({'form':form})  # render 함수 쓰는게 더 좋

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author', 'image', 'text']
    template_name_suffix = '_update'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "수정할 권한이 없습니다.")
            return HttpResponseRedirect(object.get_absolute_url())
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)


class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    # Life cycle - iOS, Android, Vue, React, Django, Rails
    # 모든 Framework는 라이프 사이클이 존재 --> 어떤 순서로 구동이 되느냐?
    # URLConf -> View -> Model 순으로 동작
    # 라이프 사이클 : 어떤 뷰를 구동할 때 그 안에서 동작하는 순서

    # 사용자가 접속했을 때 get인지 post인지 등을 결정하고 분기하는 부분
    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, "삭제할 권한이 없습니다.")
            return HttpResponseRedirect(object.get_absolute_url())
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

    # 로직을 수행하고, 템플릿을 랜더링한다.
    # def get(self, request, *args, **kwargs):
    #     object = self.get_object()
    #     if object.author != request.user:
    #         messages.warning(request, "삭제할 권한이 없습니다.")
    #         return HttpResponseRedirect(object.get_absolute_url())
    #         # 삭제 페이지에서 권한이 없다! 라고 띄우는 방법
    #         # 원래 디테일 페이지로 돌아가서 삭제에 실패했습니다! 라고 띄우는 방법
    #     else:
    #         super(PhotoDelete, self).get(request, *args, **kwargs)
    # def post(self, request, *args, **kwargs):
    #     pass
    #
    # def get_object(self, queryset=None):
    #     # 해당 쿼리셋을 이용해서 현재 페이지에 필요한 object를 인스턴스화 한다.
    #     pass
    #
    # def get_queryset(self):
    #     # 어떻게 데이터를 가져올 것이냐?
    #     pass

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'



from django.views.generic.base import View

class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        # like를 할 정보가 있다면 진행, 없다면 중단
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            #1. 어떤 포스팅?
            # url : www.naver.com/blog/like/?photo_id=1
            # request.GET.get('photo_id')
            # 단url : www.naver.com/blog/like/1/
            # path('blog/like/<int:photo_id>/'
            # kwargs['photo_id']
            # 2. 누가?
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)
            return HttpResponseRedirect('/')

class PhotoSaved(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.saved.all():
                    photo.saved.remove(user)
                else:
                    photo.saved.add(user)
            return HttpResponseRedirect('/')

class PhotoSaveList(ListView):
    model = Photo
    template_name_suffix = '_slist'

dstagram_project/photo/templates/photo/photo_create.html
{% extends 'base.html' %}

{% block title %}
Photo Create
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <form action="" method="post" enctype="multipart/form-data">  <!--인코딩 타입 설정안하면, url encording 되서 text형태로 보내짐-->
                <div class="alert alert-info">Please enter your photo information.</div>
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Upload" class="btn btn-outline-primary">
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

dstagram_project/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}

{% block title %}
Photo Delete
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete Ok">
    </form>

{% endblock %}

dstagram_project/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}
Photo Detail
{% endblock %}

{% block content %}
    <div class="col"></div>
    <div class="col-6">
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>
            <img src="{{object.image.url}}" class="card-img-top">
            {% if object.text %}
            <div class="card-body">
                <p class="card-text"> {{object.text}} </p>
                <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>
            </div>
            <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like
                        {% if user in object.like.all %}active{% endif %}">Like</a>
                        <a href="{% url 'photo:saved' object.id %}" class="float-right btn-save
                    {% if user in object.saved.all %}active{% endif %}">Save</a>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'photo:update' object.id %}" class="card-link">수정</a>
                        <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제</a>
                    </li>
            </ul>
            {% endif %}


        <!--                <form action="{% url 'photo:delete' object.id %}" method="post">-->
        <!--                    {% csrf_token %}-->
        <!--                    <input type="submit" value="Post Delete" class="btn btn-danger">-->
        <!--                </form>-->

            {# load xxx 해당 태그 기능을 지금부터 사용하겠다. #}
            {% load disqus_tags %}
            <div class="card-body">
                {% disqus_show_comments %}
            </div>
        </div>
    </div>
    <div class="col"></div>
{% endblock %}

dstagram_project/photo/templates/photo/photo_list.html
{% extends 'base.html' %}

{% block title %}
Photo List
{% endblock %}

{% block content %}
    <div class="col-6">
        {% for object in object_list %}
        <div class="card" style="margin-top:2em;">
            <div class="card-header">
                {{object.author.username}}
            </div>
            <img src="{{object.image.url}}" class="card-img-top">
            {% if object.text %}
            <div class="card-body">
                <p class="card-text"> {{object.text}} </p>
                <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>
            </div>
            {% endif %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'photo:like' object.id %}" class="float-left btn-like
                    {% if user in object.like.all %}active{% endif %}">Like</a>
                    <a href="{% url 'photo:saved' object.id %}" class="float-right btn-save
                    {% if user in object.saved.all %}active{% endif %}">Save</a>
                </li>
            </ul>
            <div class="card-body">
                <a href="{{object.get_absolute_url}}" class="card-link">댓글 달기</a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

dstagram_project/photo/templates/photo/photo_saved.html
{% extends 'base.html' %}

{% block title %}
Photo Update
{% endblock %}

{% block content %}
        <div class="col-6">
        {% for object in object_list %}
            {% if user in object.saved.all %}
            <div class="card" style="margin-top:2em;">
                <div class="card-header">
                    {{object.author.username}}
                </div>
                <img src="{{object.image.url}}" class="card-img-top">
                {% if object.text %}
                <div class="card-body">
                    <p class="card-text"> {{object.text}} </p>
                    <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>
                </div>
                {% endif %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like
                        {% if user in object.like.all %}active{% endif %}">Like</a>
                        <a href="{% url 'photo:saved' object.id %}" class="float-right btn-save
                        {% if user in object.saved.all %}active{% endif %}">Save</a>
                    </li>
                </ul>
                <div class="card-body">
                    <a href="{{object.get_absolute_url}}" class="card-link">댓글 달기</a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        </div>
{% endblock %}

dstagram_project/photo/templates/photo/photo_slist.html
{% extends 'base.html' %}

{% block title %}
Photo Update
{% endblock %}

{% block content %}
        <div class="col-6">
        {% for object in object_list %}
            {% if user in object.saved.all %}
            <div class="card" style="margin-top:2em;">
                <div class="card-header">
                    {{object.author.username}}
                </div>
                <img src="{{object.image.url}}" class="card-img-top">
                {% if object.text %}
                <div class="card-body">
                    <p class="card-text"> {{object.text}} </p>
                    <p class="card-text"><small class="text-muted"> Last updated {{object.updated}} </small></p>
                </div>
                {% endif %}
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like
                        {% if user in object.like.all %}active{% endif %}">Like</a>
                        <a href="{% url 'photo:saved' object.id %}" class="float-right btn-save
                        {% if user in object.saved.all %}active{% endif %}">Save</a>
                    </li>
                </ul>
                <div class="card-body">
                    <a href="{{object.get_absolute_url}}" class="card-link">댓글 달기</a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        </div>
{% endblock %}

dstagram_project/photo/templates/photo/photo_update.html
{% extends 'base.html' %}

{% block title %}
Photo Update
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <form action="" method="post" enctype="multipart/form-data">  <!--인코딩 타입 설정안하면, url encording 되서 text형태로 보내짐-->
                <div class="alert alert-info">Please enter your photo information.</div>
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Update" class="btn btn-outline-primary">
            </form>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}