board_project/board/urls.py
from django.urls import path
from .views import document_list, document_create, document_delete, document_detail, \
    document_update, comment_create, comment_update, comment_delete
from .views import get_data_ajax

app_name = 'board'

urlpatterns = [
    path('', document_list, name='list'),
    path('create/', document_create, name='create'),
    path('update/<int:document_id>', document_update, name='update'),
    path('delete/<int:document_id>', document_delete, name='delete'),
    path('detail/<int:document_id>', document_detail, name='detail'),
    path('comment/create/<int:document_id>', comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>', comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>', comment_delete, name='comment_delete'),
    path('ajax/get_data/', get_data_ajax, name='get_data_ajax'),
    # 클래스형뷰에서는 pk로 받아서 <int:pk>로 설정해준다.
]

board_project/config/urls.py
from django.contrib import admin
from django.urls import include, path
import allauth.account.urls

from django.conf.urls.static import static

from django.conf import settings

# allauth.urls이 궁금하면 import 뒤 urls 안에 코드 들여다 볼 수 있다.

urlpatterns = [
    path('', include('board.urls')),
    path('site_config/', admin.site.urls),  # admin 기본값 말고 다른 값 설정
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board_project/board/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
   pass

class Category(models.Model):
   name = models.CharField(max_length=20)
   slug = models.SlugField(max_length=30, db_index=True, unique=True,
                           allow_unicode=True,blank=True)
   # Board를 구현 안했기 때문에 unique 사용 / allow_unicode : 한글 사용 가능하도록 설정
   description = models.CharField(max_length=200, blank=True)
   meta_description = models.CharField(max_length=200, blank=True)
   # meta_description : 검색엔진에 제공해주는 description

   class Meta:
       # DB에 기본적으로 설정될 정렬 값
       ordering = ['slug']

   def __str__(self):
       return self.name


# User 모델을 커스텀할 경우를 위해 get_user_model 사용
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify

class Document(models.Model):
   category = models.ForeignKey(Category, on_delete=models.SET_NULL,
                                null=True, blank=True, related_name='documents')
   author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                              related_name='documents')
   # on_delete=models.SET_NULL : Category 지워진다고 삭제되지 않음
   title = models.CharField(max_length=100)
   slug = models.SlugField(max_length=120, db_index=True, unique= True,
                           allow_unicode=True, blank=True)
   # db_index=True : DB에 인덱싱 가능
   text = models.TextField()
   # upload_to : 동적으로 경로 설정 가능
   image = models.ImageField(upload_to='board_images/%Y/%m/%d')
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)

   def __str__(self):
       return self.title

   def save(self, *args, **kwargs):
       self.slug = slugify(self.title, allow_unicode=True)
       super(Document, self).save(*args, **kwargs)

   def get_absolute_url(self):
       return reverse('board:detail', args=[self.id])

class Comment(models.Model):
   # Todo : 댓글 남기기를 위해서 Form
   # Todo : 뷰는
   document = models.ForeignKey(Document, on_delete=models.CASCADE,related_name='comments')
   author = models.ForeignKey(get_user_model(),on_delete=models.SET_NULL, null=True, blank=True, related_name='comments')
   text = models.TextField()
   created = models.DateTimeField(auto_now_add=True)
   updated = models.DateTimeField(auto_now=True)
   like = models.IntegerField(default=0) # ManyToMany
   dislike = models.IntegerField(default=0)

   def __str__(self):
       return (self.author.username if self.author else "무명") + "의 댓글"

   class Meta:
       ordering = ['-id']

board_project/board/forms.py
from django import forms
from .models import Document, Comment

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ['category', 'title', 'text', 'image']

class CommentForm(forms.ModelForm):
    # text = forms.TextInput(label='댓글')
    class Meta:
        model = Comment
        fields = ['text']
        
    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       # detail 페이지에서 보여지는 이름을 원래 필드글명인 'text'에서 '댓글'로 변경
       self.fields['text'].label = ''
       self.fields['text'].widget = forms.TextInput()
       self.fields['text'].widget.attrs = {"class": "form-control", "placeholder": "댓글을 입력하세요."}

board_project/board/views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.db.models import Q
# QuerySet은 모델의 디폴트 매니저를 통해 실행한다.
import math
from .models import Document
def document_list(request):
    # QuerySet
    # 1. 객체를 선택
    # 2. 객체 생성
    # 3. 객체 필터링
    # 4. 객체 삭제
    page = int(request.GET.get('page', 1))
    # page가 없다면, default값 1로 설정  --> 127.0.0.1:8000/ 검색 --> 127.0.0.1:8000/?page=1
    # 페이지당 갯수
    paginated_by = 3
    # 1. 모델의 전체 데이터 불러오기
    # documents = Document.objects.all() # all 전체를 가져온다.  # Document.objects.filter(title__icontains="검색어")

    # request.METHOD.get --> 아이템 1개 가져온다 (데이터가 1개 이상일 경우 맨 마지막 데이터를 가져온다)
    # request.METHOD.getlist --> 리스트 형태로 가져온다.
    search_type = request.GET.getlist('search_type', None)
    # search_type = ['username', 'title', 'text']
    search_q = None
    search_key = request.GET.get('search_key', None)

    # 웹 애플리케이션 : 인프라 최적화, 소스코드 최적
    if search_key:
        # for type in search_type:
        #     if type == 'username':
        #         temp_q = Q(author__username__icontains=search_key)
        #         search_q = search_q | temp_q if search_q else temp_q
        #     else:
        #         temp_q = Q(type+"__icontains", search_key)    # 코드 수정 필요
        #         search_q = search_q | temp_q if search_q else temp_q
        # documents = get_list_or_404(Document, search_q)

        if 'title' in search_type:
            temp_q = Q(title__icontains=search_key)
            search_q = search_q | temp_q if search_q else temp_q
        if 'text' in search_type:
            temp_q = Q(text__icontains=search_key)
            search_q = search_q | temp_q if search_q else temp_q
        if 'username' in search_type:
            temp_q = Q(author__username__icontains=search_key)
            search_q = search_q | temp_q if search_q else temp_q
        documents = get_list_or_404(Document, search_q)



    # if search_key:
    #     documents = get_list_or_404(Document, title__icontains=search_key)
    else:
        # documents = get_list_or_404(Document)
        documents = Document.objects.all()
    # QuerySet 객체를 슬라이싱 할 때 [시작번호:끝번호]
    # 1페이지 - 0 ==== 3(뒷번호)
    # 2페이지 - paginated_by*(page-1) ==== 6
    # 3페이지 - paginated_by*(page-1) ==== 9
    total_count = len(documents)
    total_page = math.ceil(total_count/paginated_by)
    page_range = range(1, total_page+1)
    start_index = paginated_by * (page-1)
    end_index = paginated_by * page
    documents = documents[start_index:end_index]

    return render(request, 'board/document_list.html',
                  {'object_list':documents, 'total_page':total_page,
                   'page_range':page_range}) # context_value를 가져온다 {} - dic 형태


from .forms import DocumentForm
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
@login_required
# 로그인 한 유저만 작동하도록 진행
def document_create(request):
   # Document.object.create() - 실행과 동시에 DB에 삽입
   # 분기 - post, get
   if request.method == "POST":
       # 처리
       # request.POST : 폼에서 입력한 텍스트 데이터
       # request.FILES : 파일만 보낸다
       form = DocumentForm(request.POST, request.FILES)
       form.instance.author_id = request.user.id
       if form.is_valid():
           document = form.save()
           print(document)
           return redirect(reverse('board:detail', args=[document.id]))
   else:
       # 입력 창
       form = DocumentForm()

       return render(request, 'board/document_create.html',{'form':form})

def document_update(request, document_id):
   # 객체 불러와서, 데이터를 수정
   if request.method == "POST":
       # document = Document.objects.get(pk=document_id)
       document = get_object_or_404(Document, pk=document_id)
       form = DocumentForm(request.POST, request.FILES, instance=document)
       # document = Document.objects.get(pk=1)
       # document.id = None
       # document.save() --> 원래 기존 id 삭제하고 다시 만든다.(복사 느낌)
       # 모델폼을 사용할 때 instance를 넘겨주면, 해당 인스턴스값으로 초기화가 되고,
       # 만약 pk가 있는 instance(instance가 있으면 id 생성)라면, create가 아닌 update를 수행한다. 
       # (원래는 update 누르게 되면 create로 인식해서 동일한 입력으로 보고 수정 불가)
       # request.POST와 instance가 같이 전달되면 POST 데이터가 우선순위가 높다. --> instance 값 삭제되고, POST로 덮어씌운다.라는 느낌
       if form.is_valid():
           document = form.save()  # form.save() 하면 instance 생성 --> document 로 담는다
           return redirect(document)
   else:
       # document = Document.objects.get(pk=document_id)
       document = get_object_or_404(Document, pk=document_id)
       # modelform init with instance(model object) 구글 검색
       form = DocumentForm(instance=document)

   return render(request, 'board/document_update.html', {'form': form})

# ajax 사용하여 댓글 기능 구현
from django.template.loader import render_to_string
def comment_create(request, document_id):
    # is_ajax : ajax 기능에 의해 호출된 것인지 구분하기 위한 값
    is_ajax = request.POST.get('is_ajax')

    document = get_object_or_404(Document, pk=document_id)
    comment_form = CommentForm(request.POST)
    comment_form.instance.author_id = request.user.id
    comment_form.instance.document_id = document_id
    if comment_form.is_valid():
        comment = comment_form.save()

    # 만약 ajax에 의해 호출되었다면 redirection 없이 Json 형태로 응답
    if is_ajax:
        # html = """
        # <tr>
        # <td colspan="3">{}</td>
        # <td>{}</td>
        # <td>{}</td>
        # <td><a href="{}" class="btn btn-warning btn-sm">update</a></td>
        # <td><a href="{}" class="btn btn-danger btn-sm">delete</a></td>
        # </tr>
        # """.format(comment.text, comment.author.username, comment.created, "url1", "url2")
        # 데이터 만들어서 던져주기
        html = render_to_string('board/comment/comment_single.html',{'comment':comment})
        return JsonResponse({'html':html})
    # return redirect(reverse('board:detail', args=[document_id]))
    return redirect(document)

from .models import Comment
from django.contrib import messages

def comment_update(request, comment_id):
    is_ajax, data = (request.GET.get('is_ajax'), request.GET) if 'is_ajax' in request.GET else (request.POST.get('is_ajax', False), request.POST)

    comment = get_object_or_404(Comment, pk=comment_id)
    document = get_object_or_404(Document, pk=comment.document.id)
    if request.user != comment.author:
        messages.warning(request, "권한 없음")
        return redirect(document)

    if is_ajax:
        form = CommentForm(data, instance=comment)
        if form.is_valid():
            form.save()
            return JsonResponse({'works':True})

    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            form.save()
            return redirect(document)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'board/comment/comment_update.html', {'form':form})

def comment_delete(request, comment_id):
    is_ajax = request.GET.get('is_ajax') if 'is_ajax' in request.GET else request.POST.get('is_ajax',False)
    comment = get_object_or_404(Comment, pk=comment_id)
    document = get_object_or_404(Document, pk=comment.document.id)

    if request.user != comment.author and not request.user.is_staff and request.user != document.author:
        messages.warning(request, "권한 없음")
        return redirect(document)

    if is_ajax:
        comment.delete()
        return JsonResponse({"works":True})

    # if request.method == "POST":
    #     comment.delete()
    #     return redirect(document)
    else:
        return render(request, 'board/comment/comment_delete.html', {'object': comment})

def document_detail(request, document_id):
   # document = Document.objects.get(pk=document_id)
   document = get_object_or_404(Document, pk=document_id)

   # comment_form = CommentForm()
   # comment_form이 request.method == "POST" 위에 위치했을 때는 입력폼에 입력값이 Comment 클릭해도 없어지지 않음

   # if request.method =="POST":
   #     comment_form = CommentForm(request.POST)
   #     comment_form.instance.author_id = request.user.id
   #     comment_form.instance.document_id = document_id
   #     if comment_form.is_valid():
   #         comment = comment_form.save()

   comment_form = CommentForm()
   # comment_form이 request.method == "POST" 아래 위치할 경우, Comment 클릭하면 입력값 초기화
   comments = document.comments.all()


   return render(request, 'board/document_detail.html', {'object':document, 'comments':comments, 'comment_form':comment_form})

def document_delete(request, document_id):
   # 객체 불러와서, delete만 호출
   document = get_object_or_404(Document, pk=document_id)
   return render(request, 'board/document_delete.html', {'object':document})

from allauth.account.signals import user_signed_up
from allauth.socialaccount.models import SocialAccount
# 시그널이 발생했을 때 실행될 함수
def naver_signup(request, user, **kwargs):
    social_user = SocialAccount.objects.filter(user=user)
    if social_user.exists():
        user.last_name = social_user[0].extra_data['name']
        user.save()
# 시그널과 해당 함수를 connect
# 시그널 연결 방법 2가지 : receiver 쓰는 방법, connect 쓰는 방법
user_signed_up.connect(naver_signup)


# 일반적인 경우, 데이터 전송하기 위해 json 사용
from django.http import JsonResponse

# ajax 연습
def get_data_ajax(request):
    data = {
        'name' : 'Jonus',
        'age' : 30,
        'bloodtype' : 'O형'
    }
    return JsonResponse(data)

board_project/board/templates/board/comment_list.html
<table class="table table-striped" id="comment_list">
    <thead>
    <tr>
        <th colspan="7" class="align-left">댓글 목록</th>
    </tr>
    </thead>
    <tbody>
        {% for comment in comments %}
<!--        <tr>-->
<!--            <td colspan="3">{{comment.text}}</td>-->
<!--            <td>{{comment.author.username}}</td>-->
<!--            <td>{{comment.created}}</td>-->
<!--            <td><a href="{% url 'board:comment_update' comment.id %}" class="btn btn-warning btn-sm">update</a></td>-->
<!--            <td><a href="{% url 'board:comment_delete' comment.id %}" class="btn btn-danger btn-sm">delete</a></td>-->
<!--        </tr>-->
        {% include 'board/comment/comment_single.html' %}
        {% endfor %}
    </tbody>
</table>

board_project/board/templates/board/document_create.html
{% extends 'base.html' %}
{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Write">
</form>

{% endblock %}

board_project/board/templates/board/document_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
</form>
{% endblock %}

board_project/board/templates/board/document_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="card" style="width:30%;">
    {% if object.image %}
        <img src="{{object.image.url}}" class="card-img-top">
    {% endif %}
  <div class="card-body">
      <h5 class="card-title">{{object.title}} <span class="badge badge-info">{{object.author.username}}</span></h5>
    <p class="card-text">{{object.text}}</p>
  </div>
  <div class="card-body">
    <a href="{% url 'board:update' object.id %}" class="card-link">Update</a>
    <a href="{% url 'board:delete' object.id %}" class="card-link">Delete</a>
  </div>
</div>

<br>
<hr>
<form action="{% url 'board:comment_create' object.id %}" method="post" id="comment_form">
    {% csrf_token %}
    <input type="hidden" name="is_ajax" value="">
    <div class="form-row">
        <div class="col-8">
            {{comment_form.text}}
        </div>
        <div class="col">
            <input type="submit" value="Comment" class="btn btn-outline-primary form-control">
        </div>
    </div>
</form>
<div id="docs_comment_list_area">
    {% include 'board/comment_list.html' %}
</div>
{% endblock %}

{% block extra_script %}
<script type="text/javascript">
$(function() {
    // 1. 누구한테 이벤트를 설정할것이냐?
    // 2. 어떤 이벤트를 설정할것이냐?
    $('#comment_form').submit(function(e) {
        e.preventDefault();
        alert('댓글쓰기 완료');
        // 댓글 남기기
        $('input[name="is_ajax"]').val("1");
        url = $(this).attr('action');
        params = $(this).serialize();
        $.ajax({
            url:url,
            method:"POST",
            data:params
        }).done(function(data) {
            // 댓글 입력창 내용 비우기
            $('#id_text').val("");
            $('#comment_list tbody').prepend(data.html); // tbody 시작 지점에 요소 끼워넣기
            // is_ajax 값 초기화
            $('input[name="is_ajax"]').val("");
        });
        location.reload();
        return false;
    });

    $('.btn_comment_delete').click(function(e) {
        e.preventDefault();
        var input = confirm('댓글을 삭제하시겠습니까?');
        if (input==true) {
            comment = $(this).parents('tr'); // 버튼을 감싸고 있는 tr 찾기
            url = $(this).attr('href')+"?is_ajax=1"; // ajax 호출임을 구분할 수 있게 값 추가
            // $.ajax({}).done(function(){}); 먼저 작성하고 내용 입력해라.
            $.ajax({
                url:url
            }).done(function(data) {
                if (data.works) {
                    comment.remove(); // 해당 객체 지우기
                }
            });
        }
    });

    $('.btn_comment_update').click(function(e) {
        e.preventDefault();
        url = $(this).attr('href')+'?is_ajax=1';
        comment = $(this).parent().siblings('.comment_text'); // 원래 댓글을 찾음
        input = "<input type='text' class='update_text' value='"+comment.text()+"'>";
        comment.html(input);
        $('.update_text').keypress(function(e){
            if (e.keyCode==13) {
                text = $(this).val();
                $.ajax({
                    url:url,
                    data:{
                        text:text
                    }
                }).done(function(data) {
                    if(data.works) {
                        comment.text(text);
                    }
                });
            }
        });
        return false;
        text = prompt('수정될 댓글 내용을 입력하세요.', comment.text()); // 원래 댓글을 프롬프트로 보여줌
        if (text==null) return false; // 입력 취소면 함수 종료
        $.ajax({
            url:url,
            data:{
                text:text
            }
        }).done(function(data) {
            if(data.works) {
                comment.text(text);
            }
        });
    });
});
</script>
{% endblock %}

board_project/board/templates/board/document_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>User</th>
            <th>Date</th>
        </tr>
    </thead>
    {% for object in object_list %}
    <tbody>
        <tr>
            <td>{{object.id}}</td>
            <td><a href="{% url 'board:detail' object.id %}">{{object.title}}</a></td>
            <td>{{object.author.username}}</td>
            <td>{{object.updated}}</td>
        </tr>
    </tbody>
    {% endfor %}
</table>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% for page in page_range %}
        <li class="page-item"><a class="page-link" href="{% url 'board:list' %}?page={{page}}">{{page}}</a></li>
        {% endfor %}
    </ul>
</nav>

<form action="" method="get" id="search_form" class="">
    {%csrf_token%}
    <div class="form-row align-items-center justify-content-center">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="username" name="search_type">
            <label class="form-check-label" for="inlineCheckbox1">작성자</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="title" name="search_type" checked>
            <label class="form-check-label" for="inlineCheckbox2">제목</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="text" name="search_type">
            <label class="form-check-label" for="inlineCheckbox3">본문</label>
        </div>
    </div>
    <div class="form-row align-items-center justify-content-center">
        <div class="col-sm-3 my-1">
            <input type="text" class="form-control" placeholder="Search Keyword" name="search_key">
        </div>

        <div class="col-auto my-1">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<div class="data_area">
    데이터 입력될 곳
</div>
<a href="{% url 'board:get_data_ajax' %}" class="btn_get_data btn btn-primary">데이터</a>

{% endblock %}



<!-- ajax 연습 -->
{% block extra_script %}
<script type="text/javascrirpt">
    // 1. 버튼을 누르면 페이지 이동 안되도록
    $(function() {
        // 페이지 로딩이 끝나면 할일들
        $('.btn_get_data').click(function(e) {
            e.preventDefault(); // 버튼 클릭하면 이동 못하게 기본 기능 취소
            alert('clicked'); // 확인 위해 알림창 띄우기

        });
    });

</script>
{% endblock %}

board_project/board/templates/board/document_update.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type="submit" value="Write">
</form>

{% endblock %}